# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1STaXK9sBlk-h646jlcO9LpvQt7HROrfw
"""

import requests
from bs4 import BeautifulSoup
import re
import urllib.parse

# Define the updated list of URLs
urls = [


    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Jazzy-Jalisco-Complete-Changelog.rst#keyboard-handler",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Release-Crystal-Clemmys.rst#start-of-content",
    "https://github.com/ros2/rosidl/pull/796",
    "https://github.com/ros-visualization/qt_gui_core/issues/290",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Jazzy-Jalisco-Complete-Changelog.rst#rcl_logging_interface",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Release-Jazzy-Jalisco.rst#id24",
    "https://github.com/ros2/rmw/tree/jazzy/rmw/CHANGELOG.rst",
    "https://github.com/ros2/rcl/blob/657d9e84c73e4268176efd163e96fda73c1a76d9/rcl/include/rcl/publisher.h#L428-L439",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Jazzy-Jalisco-Complete-Changelog.rst#ament_cmake_cppcheck",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Release-Crystal-Clemmys.rst#supported-platforms",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Jazzy-Jalisco-Complete-Changelog.rst#kdl_parser",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Release-Jazzy-Jalisco.rst#player-and-recorder-are-now-exposed-as-rclcpp-components",
    "https://gazebosim.org/docs/harmonic/ros_installation",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Jazzy-Jalisco-Complete-Changelog.rst#rviz-default-plugins",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Jazzy-Jalisco-Complete-Changelog.rst#std_msgs",
    "https://github.com/ament/ament_lint/tree/jazzy/ament_lint_cmake/CHANGELOG.rst",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Jazzy-Jalisco-Complete-Changelog.rst#test-ros2trace",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Jazzy-Jalisco-Complete-Changelog.rst#test_quality_of_service",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Release-Iron-Irwini.rst#rcl-yaml-param-parser",
    "https://github.com/ros2/ros2_documentation/blob/jazzy/source/Releases/Jazzy-Jalisco-Complete-Changelog.rst#launch-testing",
    "https://github.com/ros2/ros2_tracing/pull/30"
]







# Function to fetch and clean the content of a URL
def fetch_and_clean(url):
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')

        # Extract text content and clean it
        text = soup.get_text()
        text = re.sub(r'\s+', ' ', text).strip()  # Replace multiple spaces/newlines with a single space

        # Return cleaned content
        return text
    except requests.RequestException as e:
        print(f"Error fetching {url}: {e}")
        return None

# Fetch and save content for each URL
for url in urls:
    content = fetch_and_clean(url)

    if content:
        # Extract the page name from the URL
        parsed_url = urllib.parse.urlparse(url)
        path = parsed_url.path
        page_name = path.rstrip('/').split('/')[-1]

        # Define the filename
        filename = f"{page_name}.txt"

        # Save the content to a file named after the page name
        with open(filename, 'w', encoding='utf-8') as file:
            file.write(content)
        print(f"Saved content from {url} to {filename}")
    else:
        print(f"No content found for {url}")